import '../model/phoneme.dart';

const List<Phoneme> allVowelPhonemes = [
  Phoneme(phoneme: "/i/", example: "beet"),
  Phoneme(phoneme: "/ɪ/", example: "bit"),
  Phoneme(phoneme: "/eɪ/", example: "day"),
  Phoneme(phoneme: "/æ/", example: "bat"),
  Phoneme(phoneme: "/ɑ/", example: "father"),
  Phoneme(phoneme: "/ɔ/", example: "bought"),
  Phoneme(phoneme: "/ʊ/", example: "book"),
  Phoneme(phoneme: "/u/", example: "boot"),
  Phoneme(phoneme: "/ʌ/", example: "cup"),
  Phoneme(phoneme: "/ə/", example: "sofa"),
  Phoneme(phoneme: "/ɚ/", example: "teacher"),
  Phoneme(phoneme: "/ɛ/", example: "bed"),
  Phoneme(phoneme: "/aɪ/", example: "my"),
  Phoneme(phoneme: "/aʊ/", example: "now"),
  Phoneme(phoneme: "/ɔɪ/", example: "boy"),
  Phoneme(phoneme: "/oʊ/", example: "go"),
];

const List<Phoneme> allConsonantPhonemes = [
  Phoneme(phoneme: "/p/", example: "pat"),
  Phoneme(phoneme: "/b/", example: "bat"),
  Phoneme(phoneme: "/d/", example: "dog"),
  Phoneme(phoneme: "/k/", example: "cat"),
  Phoneme(phoneme: "/t/", example: "time"),
  Phoneme(phoneme: "/g/", example: "go"),
  Phoneme(phoneme: "/m/", example: "man"),
  Phoneme(phoneme: "/n/", example: "no"),
  Phoneme(phoneme: "/ŋ/", example: "sing"),
  Phoneme(phoneme: "/f/", example: "fan"),
  Phoneme(phoneme: "/v/", example: "van"),
  Phoneme(phoneme: "/θ/", example: "think"),
  Phoneme(phoneme: "/ð/", example: "this"),
  Phoneme(phoneme: "/s/", example: "see"),
  Phoneme(phoneme: "/z/", example: "zoo"),
  Phoneme(phoneme: "/ʃ/", example: "she"),
  Phoneme(phoneme: "/ʒ/", example: "measure"),
  Phoneme(phoneme: "/h/", example: "hi"),
  Phoneme(phoneme: "/tʃ/", example: "chip"),
  Phoneme(phoneme: "/dʒ/", example: "judge"),
  Phoneme(phoneme: "/l/", example: "light"),
  Phoneme(phoneme: "/r/", example: "right"),
  Phoneme(phoneme: "/ɹ/", example: "red"),
  Phoneme(phoneme: "/j/", example: "yes"),
  Phoneme(phoneme: "/w/", example: "we"),
];
